//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubClient.RemotingServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RemotingServiceReference1.IRemotingDB")]
    public interface IRemotingDB {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemotingDB/MakeDatabasesSynced", ReplyAction="http://tempuri.org/IRemotingDB/MakeDatabasesSyncedResponse")]
        string MakeDatabasesSynced();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemotingDB/MakeDatabasesSynced", ReplyAction="http://tempuri.org/IRemotingDB/MakeDatabasesSyncedResponse")]
        System.Threading.Tasks.Task<string> MakeDatabasesSyncedAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRemotingDBChannel : SubClient.RemotingServiceReference1.IRemotingDB, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RemotingDBClient : System.ServiceModel.ClientBase<SubClient.RemotingServiceReference1.IRemotingDB>, SubClient.RemotingServiceReference1.IRemotingDB {
        
        public RemotingDBClient() {
        }
        
        public RemotingDBClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RemotingDBClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemotingDBClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemotingDBClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string MakeDatabasesSynced() {
            return base.Channel.MakeDatabasesSynced();
        }
        
        public System.Threading.Tasks.Task<string> MakeDatabasesSyncedAsync() {
            return base.Channel.MakeDatabasesSyncedAsync();
        }
    }
}
