//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubClient.InternalServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InternalServiceReference1.IInternalServices")]
    public interface IInternalServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalServices/GetData", ReplyAction="http://tempuri.org/IInternalServices/GetDataResponse")]
        string GetData(int id, bool mod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalServices/GetData", ReplyAction="http://tempuri.org/IInternalServices/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int id, bool mod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalServices/GetDataByEmail", ReplyAction="http://tempuri.org/IInternalServices/GetDataByEmailResponse")]
        string GetDataByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalServices/GetDataByEmail", ReplyAction="http://tempuri.org/IInternalServices/GetDataByEmailResponse")]
        System.Threading.Tasks.Task<string> GetDataByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalServices/GetDataBySurname", ReplyAction="http://tempuri.org/IInternalServices/GetDataBySurnameResponse")]
        string GetDataBySurname(string surname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalServices/GetDataBySurname", ReplyAction="http://tempuri.org/IInternalServices/GetDataBySurnameResponse")]
        System.Threading.Tasks.Task<string> GetDataBySurnameAsync(string surname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalServices/AddNewStudent", ReplyAction="http://tempuri.org/IInternalServices/AddNewStudentResponse")]
        string AddNewStudent(string _name, string _surn, bool batman, string _mail, float height, float weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalServices/AddNewStudent", ReplyAction="http://tempuri.org/IInternalServices/AddNewStudentResponse")]
        System.Threading.Tasks.Task<string> AddNewStudentAsync(string _name, string _surn, bool batman, string _mail, float height, float weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalServices/NukeStudent", ReplyAction="http://tempuri.org/IInternalServices/NukeStudentResponse")]
        string NukeStudent(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalServices/NukeStudent", ReplyAction="http://tempuri.org/IInternalServices/NukeStudentResponse")]
        System.Threading.Tasks.Task<string> NukeStudentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalServices/GetEntriesByName", ReplyAction="http://tempuri.org/IInternalServices/GetEntriesByNameResponse")]
        string[] GetEntriesByName(string surname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalServices/GetEntriesByName", ReplyAction="http://tempuri.org/IInternalServices/GetEntriesByNameResponse")]
        System.Threading.Tasks.Task<string[]> GetEntriesByNameAsync(string surname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalServices/SetData", ReplyAction="http://tempuri.org/IInternalServices/SetDataResponse")]
        string SetData(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalServices/SetData", ReplyAction="http://tempuri.org/IInternalServices/SetDataResponse")]
        System.Threading.Tasks.Task<string> SetDataAsync(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInternalServicesChannel : SubClient.InternalServiceReference1.IInternalServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InternalServicesClient : System.ServiceModel.ClientBase<SubClient.InternalServiceReference1.IInternalServices>, SubClient.InternalServiceReference1.IInternalServices {
        
        public InternalServicesClient() {
        }
        
        public InternalServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InternalServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InternalServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InternalServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int id, bool mod) {
            return base.Channel.GetData(id, mod);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int id, bool mod) {
            return base.Channel.GetDataAsync(id, mod);
        }
        
        public string GetDataByEmail(string email) {
            return base.Channel.GetDataByEmail(email);
        }
        
        public System.Threading.Tasks.Task<string> GetDataByEmailAsync(string email) {
            return base.Channel.GetDataByEmailAsync(email);
        }
        
        public string GetDataBySurname(string surname) {
            return base.Channel.GetDataBySurname(surname);
        }
        
        public System.Threading.Tasks.Task<string> GetDataBySurnameAsync(string surname) {
            return base.Channel.GetDataBySurnameAsync(surname);
        }
        
        public string AddNewStudent(string _name, string _surn, bool batman, string _mail, float height, float weight) {
            return base.Channel.AddNewStudent(_name, _surn, batman, _mail, height, weight);
        }
        
        public System.Threading.Tasks.Task<string> AddNewStudentAsync(string _name, string _surn, bool batman, string _mail, float height, float weight) {
            return base.Channel.AddNewStudentAsync(_name, _surn, batman, _mail, height, weight);
        }
        
        public string NukeStudent(int id) {
            return base.Channel.NukeStudent(id);
        }
        
        public System.Threading.Tasks.Task<string> NukeStudentAsync(int id) {
            return base.Channel.NukeStudentAsync(id);
        }
        
        public string[] GetEntriesByName(string surname) {
            return base.Channel.GetEntriesByName(surname);
        }
        
        public System.Threading.Tasks.Task<string[]> GetEntriesByNameAsync(string surname) {
            return base.Channel.GetEntriesByNameAsync(surname);
        }
        
        public string SetData(string data) {
            return base.Channel.SetData(data);
        }
        
        public System.Threading.Tasks.Task<string> SetDataAsync(string data) {
            return base.Channel.SetDataAsync(data);
        }
    }
}
