//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdo_wcf2.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int id, bool mod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int id, bool mod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataByEmail", ReplyAction="http://tempuri.org/IService1/GetDataByEmailResponse")]
        string GetDataByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataByEmail", ReplyAction="http://tempuri.org/IService1/GetDataByEmailResponse")]
        System.Threading.Tasks.Task<string> GetDataByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataBySurname", ReplyAction="http://tempuri.org/IService1/GetDataBySurnameResponse")]
        string GetDataBySurname(string surname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataBySurname", ReplyAction="http://tempuri.org/IService1/GetDataBySurnameResponse")]
        System.Threading.Tasks.Task<string> GetDataBySurnameAsync(string surname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNewStudentLame", ReplyAction="http://tempuri.org/IService1/AddNewStudentLameResponse")]
        string AddNewStudentLame(string _name, string _surn, bool batman, string plid, string _mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNewStudentLame", ReplyAction="http://tempuri.org/IService1/AddNewStudentLameResponse")]
        System.Threading.Tasks.Task<string> AddNewStudentLameAsync(string _name, string _surn, bool batman, string plid, string _mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TerriblyRetrieveDatabase", ReplyAction="http://tempuri.org/IService1/TerriblyRetrieveDatabaseResponse")]
        string TerriblyRetrieveDatabase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TerriblyRetrieveDatabase", ReplyAction="http://tempuri.org/IService1/TerriblyRetrieveDatabaseResponse")]
        System.Threading.Tasks.Task<string> TerriblyRetrieveDatabaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OutrageousDatabaseLeak", ReplyAction="http://tempuri.org/IService1/OutrageousDatabaseLeakResponse")]
        string[] OutrageousDatabaseLeak();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OutrageousDatabaseLeak", ReplyAction="http://tempuri.org/IService1/OutrageousDatabaseLeakResponse")]
        System.Threading.Tasks.Task<string[]> OutrageousDatabaseLeakAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NukeStudent", ReplyAction="http://tempuri.org/IService1/NukeStudentResponse")]
        string NukeStudent(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NukeStudent", ReplyAction="http://tempuri.org/IService1/NukeStudentResponse")]
        System.Threading.Tasks.Task<string> NukeStudentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEntriesByName", ReplyAction="http://tempuri.org/IService1/GetEntriesByNameResponse")]
        string[] GetEntriesByName(string surname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetEntriesByName", ReplyAction="http://tempuri.org/IService1/GetEntriesByNameResponse")]
        System.Threading.Tasks.Task<string[]> GetEntriesByNameAsync(string surname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetData", ReplyAction="http://tempuri.org/IService1/SetDataResponse")]
        string SetData(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetData", ReplyAction="http://tempuri.org/IService1/SetDataResponse")]
        System.Threading.Tasks.Task<string> SetDataAsync(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : sdo_wcf2.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<sdo_wcf2.ServiceReference1.IService1>, sdo_wcf2.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int id, bool mod) {
            return base.Channel.GetData(id, mod);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int id, bool mod) {
            return base.Channel.GetDataAsync(id, mod);
        }
        
        public string GetDataByEmail(string email) {
            return base.Channel.GetDataByEmail(email);
        }
        
        public System.Threading.Tasks.Task<string> GetDataByEmailAsync(string email) {
            return base.Channel.GetDataByEmailAsync(email);
        }
        
        public string GetDataBySurname(string surname) {
            return base.Channel.GetDataBySurname(surname);
        }
        
        public System.Threading.Tasks.Task<string> GetDataBySurnameAsync(string surname) {
            return base.Channel.GetDataBySurnameAsync(surname);
        }
        
        public string AddNewStudentLame(string _name, string _surn, bool batman, string plid, string _mail) {
            return base.Channel.AddNewStudentLame(_name, _surn, batman, plid, _mail);
        }
        
        public System.Threading.Tasks.Task<string> AddNewStudentLameAsync(string _name, string _surn, bool batman, string plid, string _mail) {
            return base.Channel.AddNewStudentLameAsync(_name, _surn, batman, plid, _mail);
        }
        
        public string TerriblyRetrieveDatabase() {
            return base.Channel.TerriblyRetrieveDatabase();
        }
        
        public System.Threading.Tasks.Task<string> TerriblyRetrieveDatabaseAsync() {
            return base.Channel.TerriblyRetrieveDatabaseAsync();
        }
        
        public string[] OutrageousDatabaseLeak() {
            return base.Channel.OutrageousDatabaseLeak();
        }
        
        public System.Threading.Tasks.Task<string[]> OutrageousDatabaseLeakAsync() {
            return base.Channel.OutrageousDatabaseLeakAsync();
        }
        
        public string NukeStudent(int id) {
            return base.Channel.NukeStudent(id);
        }
        
        public System.Threading.Tasks.Task<string> NukeStudentAsync(int id) {
            return base.Channel.NukeStudentAsync(id);
        }
        
        public string[] GetEntriesByName(string surname) {
            return base.Channel.GetEntriesByName(surname);
        }
        
        public System.Threading.Tasks.Task<string[]> GetEntriesByNameAsync(string surname) {
            return base.Channel.GetEntriesByNameAsync(surname);
        }
        
        public string SetData(string data) {
            return base.Channel.SetData(data);
        }
        
        public System.Threading.Tasks.Task<string> SetDataAsync(string data) {
            return base.Channel.SetDataAsync(data);
        }
    }
}
